version: '2'
services:
    <%= baseName.toLowerCase() %>-elasticsearch:
        container_name: <%= baseName.toLowerCase() %>-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/<%= baseName %>/elasticsearch/:/usr/share/elasticsearch/data/
        # Uncomment to have the server accessible from outside Docker
        # ports:
        #     - 9200:9200
        #     - 9300:9300
